### ISSUE TITLE
cell2location version conflict

### ISSUE THREAD

**Issue by mih1997** [omnideconv/spacedeconv#90]
When installing with pak::pkg_install("omnideconv/spacedeconv", dependencies = T) ，the installation of cell2location  is canceled because of  conflicting dependencies. When I installed cell2location manually,the  proper environment of cell2location installation can not match the spacedeconv environment.

### Brief description of the problem

ERROR: Cannot install cell2location because these package versions have conflicting dependencies.

The conflict is caused by:
    scvi-tools 0.20.3 depends on jaxlib>=0.4.3
    scvi-tools 0.20.2 depends on jaxlib>=0.4.3
    scvi-tools 0.20.1 depends on jaxlib>=0.4.3
    scvi-tools 0.20.0 depends on jaxlib
    scvi-tools 0.19.0 depends on jaxlib
    scvi-tools 0.18.0 depends on jaxlib
    scvi-tools 0.17.4 depends on jaxlib
    scvi-tools 0.17.3 depends on jaxlib
    scvi-tools 0.17.2 depends on jaxlib
    scvi-tools 0.17.1 depends on jaxlib
    scvi-tools 0.17.0 depends on jaxlib

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by czackl** [comment]
Hi, 

Thanks for using our package! Unfortunately i have not been able to replicate this issue. We have multiple GitHub Pipelines running which are checking the innstallation of spacedeconv with each commit. For us the python dependencies install without error in a separate conda environment called r-omnideconv. 

Maybe try installing the latest version. 
If you are running spacedeconv in a HPC environment it could also make sense to install R and required system dependencies in a separte conda environment. 

Please also note that spacedeconv is a project still under development, so feel free to contact us about issues and ideas you have. Feedback is always welcome. 

Hope that helps

**Comment by czackl** [comment]
Did this solve your issue? Feel free to reach out for additional help.
